build-job:
  stage: build
  image: ubuntu:latest

  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - sudo dpkg --add-architecture i386
    - sudo apt update
    - apt-get install -y --no-install-recommends \
      build-essential curl procps clang lld make binutils \
      libcurl4-openssl-dev libatomic1 libreadline-dev libarchive-dev \
      libgtk-3-dev pkg-config \
      zlib1g-dev upx-ucl upx \
      libc6:i386 libstdc++6:i386 libcurl4:i386

  script:
    - echo "[TASKS - BUILD] Compiling with debug flags..."
    - make debug
    - file watchdogs.debug

  artifacts:
    paths:
      - watchdogs.debug
    expire_in: 1 week
